protected/models/Cliente.php
<?php

/**
 * This is the model class for table "cliente".
 *
 * The followings are the available columns in table 'cliente':
 * @property integer $id
 * @property string $razonSocial
 * @property string $direccion
 * @property string $nombreFantasia
 * @property string $contacto
 * @property string $cuit
 * @property string $telefonos
 * @property string $PDpto
 * @property string $email
 * @property string $fax
 * @property string $observaciones
 * @property integer $id_rubro
 * @property string $direccionDeposito
 * @property integer $codViajante
 * @property string $cp
 * @property string $zp
 * @property integer $categoriaIva
 * @property string $tipoCliente
 * @property integer $exeptuaIIB
 * @property string $pieFactura
 * @property double $saldoActual
 * @property string $saldoConciliado
 * @property string $fechaConciliacion
 *
 * The followings are the available model relations:
 * @property CodigoPostal $oCp
 * @property RubroClientes $oRubro
 * @property CategoriaIva $oCategoriaIva
 * @property Viajante $oViajante
 * @property Comprobante[] $aComprobante
 * @property NotaEntrega[] $aNotaEntrega
 */

class Cliente extends CActiveRecord
{
    public $atencionSobre = '';
    public $sLocalidad = '';
    public $sProvincia = '';

	public static $tipoPersona = array(
		'E' => 'Empresa',
		'P' => 'Persona',
	);
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'cliente';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		 return array(
            array('codViajante, cp, zp, categoriaIva, direccion, razonSocial', 'required'),
            array('id, id_rubro, codViajante, categoriaIva,exeptuaIIB', 'numerical', 'integerOnly'=>true),
            array('saldoActual', 'numerical'),
            array('razonSocial, telefonos', 'length', 'max'=>40),
            array('fax, direccion, PDpto', 'length', 'max'=>30),
            array('nombreFantasia, direccionDeposito', 'length', 'max'=>60),
            array('contacto, email', 'length', 'max'=>50),
            array('cuit', 'length', 'max'=>13),
            array('cp, zp', 'length', 'max'=>4),
            array('tipoCliente', 'length', 'max'=>2),
            array('id,observaciones,pieFactura, fechaConciliacion', 'safe'),
            array('cuit','validarCuit'),
            // The following rule is used by search().
            // @todo Please remove those attributes that should not be searched.
            array('id, razonSocial, direccion, nombreFantasia, contacto, cuit, telefonos, PDpto, email, fax, observaciones, id_rubro, direccionDeposito, codViajante, cp, zp, categoriaIva, tipoCliente, exeptuaIIB, pieFactura, saldoActual, saldoConciliado, fechaConciliacion', 'safe', 'on'=>'search'),
        );
	}

    public function validarCuit($attribute){
        //$this->$attribute
        if($this->isNewRecord){
            if($this->categoriaIva != 5 && $this->categoriaIva != 6 && $this->categoriaIva != 7 && $this->categoriaIva != 8){
                if($this->cuit == ''){

                    $this->addError($attribute, 'El cuit no puede ser vacio');
                }else{
                    if (!self::isValidCuit($this->cuit)){
                        $this->addError($attribute, 'El cuit no es válido');
                    }
                }
            }
        }
    }

    public static function isValidCuit($cuit) {
        $digits = array();
        if (strlen($cuit) != 11) return false;
        for ($i = 0; $i < strlen($cuit); $i++) {
            if (!ctype_digit($cuit[$i])) return false;
            if ($i < 11) {
                $digits[] = $cuit[$i];
            }
        }
        $acum = 0;
        foreach (array(5, 4, 3, 2, 7, 6, 5, 4, 3, 2) as $i => $multiplicador) {
            $acum += $digits[$i] * $multiplicador;
        }
        $cmp = 11 - ($acum % 11);
        if ($cmp == 11) $cmp = 0;
        if ($cmp == 10) $cmp = 9;
        return ($cuit[10] == $cmp);
    }

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'oCp' => array(self::BELONGS_TO, 'CodigoPostal', 'cp'),
            'oRubro' => array(self::BELONGS_TO, 'RubroClientes', 'id_rubro'),
            'oCategoriaIva' => array(self::BELONGS_TO, 'CategoriaIva', 'categoriaIva'),
            'oViajante' => array(self::BELONGS_TO, 'Viajante', 'codViajante'),
            'aComprobante' => array(self::HAS_MANY, 'Comprobante', 'Id_Cliente'),
            'aNotaEntrega' => array(self::HAS_MANY, 'NotaEntrega', 'idCliente'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
            'razonSocial' => 'Razon Social',
            'direccion' => 'Direccion',
            'nombreFantasia' => 'Nombre Fantasia',
            'contacto' => 'Contacto',
            'cuit' => 'Cuit',
            'telefonos' => 'Telefonos',
            'PDpto' => 'Pdpto',
            'email' => 'Email',
            'fax' => 'Fax',
            'observaciones' => 'Observaciones',
            'id_rubro' => 'Id Rubro',
            'direccionDeposito' => 'Direccion Deposito',
            'codViajante' => 'Cod Viajante',
            'cp' => 'Cp',
            'zp' => 'Zp',
            'categoriaIva' => 'Categoria Iva',
            'tipoCliente' => 'Tipo Cliente',
            'exeptuaIIB' => 'Exeptua IIB',
            'saldoActual' => 'Saldo Actual',
            'atencionSobre' => 'Atencion Sr.//a.',
            'saldoConciliado' => Yii::t('application', 'Saldo Conciliado'),
            'fechaConciliacion' => Yii::t('application', 'Fecha Conciliacion'),
		);
	}

	public function getTitle(){
	    if ($this->razonSocial == ''){
	        return $this->nombreFantasia;
        }else{
            return $this->razonSocial;
        }
    }

	public function getLocalidad() {
		$oLocalidad = CodigoPostal::model()->findByAttributes(array('codigoPostal'=>$this->cp,'zp' => $this->zp));
		$sLocalidad = '';
		if($oLocalidad != NULL){
			$sLocalidad = $oLocalidad->nombrelocalidad;
		}
		return $sLocalidad;
	}

	public function getProvincia() {
		$oCodigoPostal = CodigoPostal::model()->findByAttributes(array('codigoPostal'=>$this->cp,'zp' => $this->zp));
		$sProvincia = '';
		if($oCodigoPostal != NULL){
			$sProvincia = $oCodigoPostal->oProvincia->nombre;
		}
		return $sProvincia;
	}

    public function getNro_Puesto_Venta(){
        $oLocalidad = CodigoPostal::model()->findByAttributes(array('codigoPostal' => $this->cp, 'zp' => $this->zp));
        if ($oLocalidad != null && $oLocalidad->id_provincia != 'E') {
            return 9;
        } else {
            return 10;
        }
    }


	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		 $criteria->compare('id',$this->id);
        $criteria->compare('razonSocial',$this->razonSocial,true);
        $criteria->compare('direccion',$this->direccion,true);
        $criteria->compare('nombreFantasia',$this->nombreFantasia,true);
        $criteria->compare('contacto',$this->contacto,true);
        $criteria->compare('cuit',$this->cuit,true);
        $criteria->compare('telefonos',$this->telefonos,true);
        $criteria->compare('PDpto',$this->PDpto,true);
        $criteria->compare('email',$this->email,true);
        $criteria->compare('fax',$this->fax,true);
        $criteria->compare('observaciones',$this->observaciones,true);
        $criteria->compare('id_rubro',$this->id_rubro);
        $criteria->compare('direccionDeposito',$this->direccionDeposito,true);
        $criteria->compare('codViajante',$this->codViajante);
        $criteria->compare('cp',$this->cp,true);
        $criteria->compare('zp',$this->zp,true);
        $criteria->compare('categoriaIva',$this->categoriaIva);
        $criteria->compare('tipoCliente',$this->tipoCliente,true);
        $criteria->compare('saldoActual',$this->saldoActual);
        $criteria->compare('saldoConciliado',$this->saldoConciliado,true);
        $criteria->compare('fechaConciliacion',$this->fechaConciliacion,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function searchWP()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria=new CDbCriteria;

        $criteria->compare('id',$this->id);
        $criteria->compare('razonSocial',$this->razonSocial,true);
        $criteria->compare('direccion',$this->direccion,true);
        $criteria->compare('nombreFantasia',$this->nombreFantasia,true);
        $criteria->compare('contacto',$this->contacto,true);

protected/views/factura/_formBCK.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'factura-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Los campos <span class="required">*</span> son obligatorios.</p>

	<div class="alert alert-block alert-error" style="display:none;" id="errorFactura"></div>
	<div class="alert alert-block alert-success" style="display:none;" id="okFactura">Datos Guardados Correctamente !</div>

<?php echo $form->errorSummary($model); ?>

<div class="content-fluid">
	<div class="row-fluid">

		<div class="span3">
			<?php echo $form->textFieldRow($model,'clase',array('class'=>'span12','maxlength'=>1)); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Nro_Puesto_Venta',array('class'=>'span12')); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Nro_Comprobante',array('class'=>'span12','maxlength'=>8)); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Iva_Responsable',array('class'=>'span12','maxlength'=>1)); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Nro_Viajante',array('class'=>'span12')); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Id_Cliente',array('class'=>'span12')); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'fecha',array('class'=>'span12')); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Moneda',array('class'=>'span12','maxlength'=>8)); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Total_Neto',array('class'=>'span12')); ?>
		</div>
		<div class="span3">
			<?php echo $form->textAreaRow($model,'Observaciones',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Id_Camion',array('class'=>'span12')); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Descuento1',array('class'=>'span12')); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Descuento2',array('class'=>'span12')); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Total_Final',array('class'=>'span12')); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Enviada',array('class'=>'span12')); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Recibida',array('class'=>'span12')); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Otro_Iva',array('class'=>'span12')); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'CAE',array('class'=>'span12','maxlength'=>14)); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Vencim_CAE',array('class'=>'span12')); ?>
		</div>
		<div class="span3">
			<?php echo $form->textFieldRow($model,'Ing_Brutos',array('class'=>'span12')); ?>
		</div>
		
	</div>
</div>

<div class="form-actions">
	<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Crear' : 'Guardar',
		)); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/factura/_search.php
     <?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>
     <div class="row-fluid">
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'id',array('class'=>'span12')); ?>
         </div>
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'clase',array('class'=>'span12','maxlength'=>1)); ?>
         </div>
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'Nro_Puesto_Venta',array('class'=>'span12')); ?>
         </div>
     </div>
     <div class="row-fluid">
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'Nro_Comprobante',array('class'=>'span12','maxlength'=>8)); ?>
         </div>
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'Iva_Responsable',array('class'=>'span12','maxlength'=>1)); ?>
         </div>
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'Nro_Viajante',array('class'=>'span12')); ?>
         </div>
     </div>
     <div class="row-fluid">
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'Id_Cliente',array('class'=>'span12')); ?>
         </div>
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'fecha',array('class'=>'span12')); ?>
         </div>
        <div class="span4">
		    <?php echo $form->textFieldRow($model,'Moneda',array('class'=>'span12','maxlength'=>8)); ?>
         </div>
     </div>
     <div class="row-fluid">
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'Total_Neto',array('class'=>'span12')); ?>
         </div>
        <div class="span4">
		    <?php echo $form->textAreaRow($model,'Observaciones',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>
         </div>
        <div class="span4">
		    <?php echo $form->textFieldRow($model,'Id_Camion',array('class'=>'span12')); ?>
         </div>
     </div>
     <div class="row-fluid">
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'Descuento1',array('class'=>'span12')); ?>
         </div>
        <div class="span4">
		    <?php echo $form->textFieldRow($model,'Descuento2',array('class'=>'span12')); ?>
         </div>
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'Total_Final',array('class'=>'span12')); ?>
         </div>
     </div>
     <div class="row-fluid">
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'Enviada',array('class'=>'span12')); ?>
         </div>
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'Recibida',array('class'=>'span12')); ?>
         </div>
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'Otro_Iva',array('class'=>'span12')); ?>
         </div>
     </div>
     <div class="row-fluid">
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'CAE',array('class'=>'span12','maxlength'=>14)); ?>
         </div>
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'Vencim_CAE',array('class'=>'span12')); ?>
         </div>
         <div class="span4">
		    <?php echo $form->textFieldRow($model,'Ing_Brutos',array('class'=>'span12')); ?>
         </div>
     </div>

            <?php $this->widget('bootstrap.widgets.TbButton', array(
                'buttonType' => 'submit',
                'type'=>'primary',
                'label'=>'Buscar',
            )); ?>


<?php $this->endWidget(); ?>

protected/views/factura/_view.php
<?php
/* @var $this FacturaController */
/* @var $data Factura */
?>

<div class="view">

		<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('clase')); ?>:</b>
	<?php echo CHtml::encode($data->clase); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Nro_Puesto_Venta')); ?>:</b>
	<?php echo CHtml::encode($data->Nro_Puesto_Venta); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Nro_Comprobante')); ?>:</b>
	<?php echo CHtml::encode($data->Nro_Comprobante); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Iva_Responsable')); ?>:</b>
	<?php echo CHtml::encode($data->Iva_Responsable); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Nro_Viajante')); ?>:</b>
	<?php echo CHtml::encode($data->Nro_Viajante); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Id_Cliente')); ?>:</b>
	<?php echo CHtml::encode($data->Id_Cliente); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('fecha')); ?>:</b>
	<?php echo CHtml::encode($data->fecha); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Moneda')); ?>:</b>
	<?php echo CHtml::encode($data->Moneda); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Total_Neto')); ?>:</b>
	<?php echo CHtml::encode($data->Total_Neto); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Observaciones')); ?>:</b>
	<?php echo CHtml::encode($data->Observaciones); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Id_Camion')); ?>:</b>
	<?php echo CHtml::encode($data->Id_Camion); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Descuento1')); ?>:</b>
	<?php echo CHtml::encode($data->Descuento1); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Descuento2')); ?>:</b>
	<?php echo CHtml::encode($data->Descuento2); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Total_Final')); ?>:</b>
	<?php echo CHtml::encode($data->Total_Final); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Enviada')); ?>:</b>
	<?php echo CHtml::encode($data->Enviada); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Recibida')); ?>:</b>
	<?php echo CHtml::encode($data->Recibida); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Otro_Iva')); ?>:</b>
	<?php echo CHtml::encode($data->Otro_Iva); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('CAE')); ?>:</b>
	<?php echo CHtml::encode($data->CAE); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Vencim_CAE')); ?>:</b>
	<?php echo CHtml::encode($data->Vencim_CAE); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Ing_Brutos')); ?>:</b>
	<?php echo CHtml::encode($data->Ing_Brutos); ?>
	<br />

	*/ ?>

</div>

protected/views/factura/viewPdf.php
<div class="framePpal" style="font-style: normal !important;" >
    <div class="container-fluid" style="width: 100%;margin: 0px;padding: 0px;">
        <div class="row-fluid" id="header1" style="">
            <div class="span5" style="padding-top: 10px;">
                <img src="<?=Yii::getPathOfAlias('webroot.images')?>/logoFactura.jpg" width="280px;">
            </div>
            <div class="span3" id="tipoFactura" style="text-align: center;">
                <h1><?=$model->clase?><br><?=$copia?></h1>
            </div>
            <div class="span3" style="font-weight: bold;font-size: 30;text-align: center;padding-top: 30px;">
                FACTURA
            </div>
        </div>
        <div class="row-fluid"  id="header2" style="height: 100px; vertical-align: bottom;border-bottom: 1px solid black;width: 100%">
            <?=$model->Header?>
        </div>
        <div class="row-fluid" id="header3" style="height: 70px; vertical-align: bottom;border-bottom: 1px solid black;width: 100%">
            <div class="span7">
                Cliente:	<?=$model->oCliente->title?><br>
                Domicilio: <?=$model->oCliente->direccion?><br>
                Localidad: (<?=$model->oCliente->cp?>) <?=(strtoupper($model->oCliente->localidad))?> - <?=strtoupper($model->oCliente->provincia)?><br>
                Condicion de venta:<?=Comprobante::$aCondicion[$model->condicion]?><br>
            </div>
            <div class="span5">
                N° Cuenta: <?=$model->Id_Cliente?><br>
                Cond. Frente al IVA: <?=$model->oIvaResponsable->nombre?><br>
                CUIT: 	<?=$model->oCliente->cuit?><br>

            </div>
        </div>
        <div class="row-fluid" id="prods" style="">
            <?php $this->widget('bootstrap.widgets.TbGridView',array(
                'id'=>'prod-factura-grid',
                'template' => '{items}',
                'dataProvider'=>$aProdFactura->searchWP(),
                'enableSorting' => false,
                'htmlOptions' => array(
                    'style' => 'width:100%;',
                ),
                'columns'=>array(
                    array(
                        'name' => 'idArtVenta',
                        'header' => 'Codigo',
                        'value' => '$data->oArtVenta->codigo',
                        'htmlOptions' => array('style' => 'text-align:center;'),
                        'headerHtmlOptions' => array('style' => 'text-align:center;width:80px;'),
                    ),
                    array(
                        'name' => 'idArtVenta',
                        'header' => 'Producto',
                        'value' => '$data->descripcion',
                        'headerHtmlOptions' => array('style' => 'text-align:left;'),
                        'htmlOptions' => array('style' => 'width:350px;'),
                    ),

                    array(
                        'name' => 'cantidad',
                        'header' => 'Cant.',
                        'value' => 'number_format($data->cantidad,2,",",".")',
                        'headerHtmlOptions' => array('style' => 'text-align:right;'),
                        'htmlOptions' => array('style' => 'text-align:right;width:80px;'),
                    ),
                    array(
                        'name' => 'precioUnitario',
                        'header' => 'P.U.',
                        'value' => 'number_format($data->precioUnitario,2,",",".")',
                        'headerHtmlOptions' => array('style' => 'text-align:right;'),
                        'htmlOptions' => array('style' => 'text-align:right;width:80px;'),
                    ),

                    array(
                        'name' => 'SubTotal',
                        'value' => 'number_format($data->SubTotal,2,",",".")',
                        //'value' => '$data->SubTotal',
                        'header' => 'Total',
                        'htmlOptions' => array('style' => 'text-align:right;'),
                        'headerHtmlOptions' => array('style' => 'text-align:right;width:130px;'),
                        //'footerHtmlOptions' => array('style' => 'text-align:right;width:100px;'),

                    ),

                ),
            )); ?>
        </div>
        <div class="row-fluid" style="width: 100%;padding: 3px;">
            <?=$model->getItemsFooter()?>
        </div>
        <div class="row-fluid" style="width: 100%;padding-left: 62px;font-size:14">
            <b>SON PESOS <?=ComponentesComunes::numtoletras($model->Total_Final)?><br/></b>
            <?php
            if($model->clase == 'B'){
               echo '<b>Recibí importe por ERCA S.R.L.</b>';
            }

            ?>
        </div>
        <div class="row-fluid" style="width: 100%;padding: 3px;font-size: 10">
            <p id="losPagos"><span id="laMercaderia">LA MERCADERIA VIAJA POR CUENTA Y RIESGO DEL COMPRADOR. Rogamos revisar la mercadería antes de recibirla.</span><br>Los pagos deben efctuarse a la orden de ERCA SRL. Todo pago fuera de termino devengará intereses punitorios. Tipo de cambio de venta en dolares EEUU. El monto en pesos de esta factura se ajustará conforme a la variación del tipo de cambio vendedor del BNA de la fecha efectiva de acreditación del pago.</p>
            <?=$model->oCliente->pieFactura?>
        </div>
        <div class="row-fluid" style="width: 100%;padding: 3px;">
            <div class="span6" style="padding-left: 15px;">
                <?php
                if($model->CAE != '' & $model->CAE != ''){
                }
                $this->widget('ext.qrcode.QRCodeGenerator',array(
                    'data' => $model->getQrUrl(),
                    'subfolderVar' => 'qr',
                    'matrixPointSize' => 5,
                    'filename' => "F-".$model->Nro_Puesto_Venta."-".$model->id.".jpg",
                    'filePath'=>Yii::getPathOfAlias("webroot")."/upload",
                    'fileUrl'=>Yii::getPathOfAlias("webroot")."/upload",                    
                    'displayImage'=>true, // default to true, if set to false display a URL path
                    'errorCorrectionLevel'=>'L', // available parameter is L,M,Q,H
                    'matrixPointSize'=>4, // 1 to 10 only
                    'displayImage'=>true,
                    'imageTagOptions' => ['width'=>"90px",'height'=>"90px"]
                ))
                ?>
                <br>
            </div>
            <div class="span5">
                <?=($model->CAE != '' & $model->CAE != '')? 'AFIP CPTE AUTORIZADO' : '' ?>
                CAE Nro: <?=$model->CAE?><br>
                Fecha Vto CAE: <?=($model->CAE != '' & $model->CAE != '')? ComponentesComunes::fechaFormateada($model->Vencim_CAE) : ''?>
            </div>
        </div>
        <div class="row-fluid" style="width: 100%;padding: 3px;text-align: left;">

        </div>
    </div>
</div>